version: '3.9'
services:
  minio:
    image: minio/minio:RELEASE.2025-02-28T09-55-16Z
    container_name: minio
    command: server /data --console-address ":9090"
    restart: always
    ports:
      - 9998:9000
      - 9999:9090
    volumes:
      - minio-vol:/data
    environment:
      - MINIO_ROOT_USER=$MINIO_ROOT_USER
      - MINIO_ROOT_PASSWORD=$MINIO_ROOT_PASSWORD
    networks:
      - minio_net
networks:
  minio_net:
    external: true
volumes:
  minio-vol:
    driver: local
    driver_opts:
      type: none
      device: /minio/data
      o: bind
